### ISSUE TITLE
按照你的代码测试出错啊

### ISSUE THREAD

**Issue by ForceLorda** [flc1125/dysms#2]
{#209 ▼
  +"Message": "模板变量缺少对应参数值"
  +"RequestId": "7AF51BAA-21A7-4C5D-8F9C-1359950DB1B9"
  +"Code": "isv.TEMPLATE_MISSING_PARAMETERS"
}
难道又不行了

**Comment by flc1125** [comment]
你这个应该是你的模版参数漏了。代码本身应该没问题！

**Comment by flc1125** [comment]
是不是纯文本短信（不需要传模板变量）的会报这个错误，如果是，新版已经修复！
