### ISSUE TITLE
报错code 11

### ISSUE THREAD

**Issue by hickey666** [flc1125/dysms#3]
stdClass Object ( [code] => 11 [msg] => Insufficient isv permissions [sub_code] => isv.permission-api-package-limit [sub_msg] => scope ids is 11022 11600 11863 [request_id] => 43w8i9369ftv )

上面这个是报错信息，我用的是阿里大鱼，这个是不是不能用于阿里大于

**Comment by flc1125** [comment]
这个是阿里短信，不是阿里大于，两个虽是阿里旗下，但业务和接口完全不同！阿里大于请参考：https://github.com/flc1125/alidayu
