### ISSUE TITLE
本地测试正常，可以发送短信，上传到服务器就没结果了

### ISSUE THREAD

**Issue by githubyyf** [flc1125/dysms#5]
在本地测试正常，可以正常发送信息，打印返回值，
在服务器上就不行了，请求url后的返回结果是null,这是怎么回事？是服务器上php curl的问题吗？

**Comment by flc1125** [comment]
先自行查看php错误日志。

参考方向：

- PHP版本
- curl模块
- 网络问题
- 调用程序本身错误

**Comment by githubyyf** [comment]
不好意思，已经找到问题了，是因为我们服务器是内网的一台主机，运维配置连接外网出了问题。。。。。所以，所有的检测都是正常的，但是请求url的时候连接超时，但没有任何提示信息

**Comment by flc1125** [comment]
:smiley::smiley:
